name: Challenge - CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 9,11,15,18 * * 1,2,3,4,5'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout projeto
        uses: actions/checkout@v2 

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: instalando suas depedencias
        run: npm install

      - name: Configuração do Webdriveio instalando sua dependencia
        run: npm i @wdio/selenium-standalone-service --save-dev

      - name: Execução dos testes 
        run: npx codeceptjs run
    